name: findmyroute_a4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - osmnx>=1.3.0
  - folium>=0.14.0
  - geopandas>=0.12.0
  - networkx>=3.0
  - jupyterlab
  - notebook
  - matplotlib
  - numpy
  - pandas
  - shapely
  - rtree
  - pip
  - pip:
      - contextily>=1.3.0
